### ISSUE TITLE
Getting error when pushing event from stream

### ISSUE THREAD

**Issue by tvnoppen** [matrus2/dynamodb-stream-elasticsearch#28]
Hi,
I just set up the Lambda according to the example in the readme.
Every time the Lambda tries to push an event to ES I get below error:
`Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Error Error: ResponseError: Response Error",
    "stack": [
        "Error: Error Error: ResponseError: Response Error",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:54)",
        "    at callback (/var/runtime/CallbackContext.js:42:7)",
        "    at /var/runtime/CallbackContext.js:105:16",
        "    at /var/task/dynamodbtoelasticsearch.js:13:9",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}`

This is the event that comes in from DynamoDb stream:
{
    "Records": [
        {
            "eventID": "85768e0266331b54312689af3a20ee54",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "eu-west-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1591888165,
                "Keys": {
                    "id": {
                        "S": "a2d60de1-dac9-4ace-b291-34e7650a25a3"
                    },
                    "account": {
                        "S": "pj5bdbYHjSUoKfucCtHcRZ"
                    }
                },
                "NewImage": {
                    "comments": {
                        "L": [
                            {
                                "M": {
                                    "text": {
                                        "S": "Tijdens haar stage op de afdeling Moordzaken van het plaatselijk Openbaar Ministerie, kwam Allison DuBois erachter dat ze een speciale gave had. Als ze de foto's en ander materiaal van de plaats delict klaarlegde voor de rechtszaak, zag ze de misdaad door de ogen van de dader. In plaats van haar gave te onderdrukken, besloot ze haar mogelijkheden ten volle te benutten. Nu helpt ze justitie bij het vinden van lichamen, het ontdekken van bewijs en het oplossen van zaken."
                                    }
                                }
                            }
                        ]
                    },
                    "seriesindex": {
                        "N": "0"
                    },
                    "languages": {
                        "L": [
                            {
                                "M": {
                                    "code": {
                                        "S": "nld"
                                    }
                                }
                            }
                        ]
                    },
                    "datas": {
                        "L": [
                            {
                                "M": {
                                    "name": {
                                        "S": "a2d60de1-dac9-4ace-b291-34e7650a25a3"
                                    },
                                    "format": {
                                        "S": "epub"
                                    }
                                }
                            }
                        ]
                    },
                    "title": {
                        "S": "Kus ze niet vaarwel"
                    },
                    "type": {
                        "S": "book"
                    },
                    "tags": {
                        "L": [
                            {
                                "M": {
                                    "name": {
                                        "S": "Esoterie"
                                    }
                                }
                            }
                        ]
                    },
                    "cover": {
                        "M": {
                            "name": {
                                "S": "a2d60de1-dac9-4ace-b291-34e7650a25a3"
                            },
                            "format": {
                                "S": "jpg"
                            }
                        }
                    },
                    "lastmodified": {
                        "S": "2011-09-04T11:56:38.237+02:00"
                    },
                    "ratings": {
                        "L": [
                            {
                                "M": {
                                    "value": {
                                        "N": "10"
                                    }
                                }
                            }
                        ]
                    },
                    "publishers": {
                        "L": [
                            {
                                "M": {
                                    "name": {
                                        "S": "A.W. Bruna LeV."
                                    }
                                }
                            }
                        ]
                    },
                    "id": {
                        "S": "a2d60de1-dac9-4ace-b291-34e7650a25a3"
                    },
                    "publishingdate": {
                        "S": "2010-03-07T00:00:00+01:00"
                    },
                    "account": {
                        "S": "pj5bdbYHjSUoKfucCtHcRZ"
                    },
                    "authors": {
                        "L": [
                            {
                                "M": {
                                    "name": {
                                        "S": "Allison Dubois"
                                    }
                                }
                            }
                        ]
                    }
                },
                "SequenceNumber": "100000000058339634495",
                "SizeBytes": 1014,
                "StreamViewType": "NEW_IMAGE"
            },
            "eventSourceARN": "arn:aws:dynamodb:eu-west-1:xxxxxxxxxxxx:table/xxxxxxxxx/stream/2020-06-11T14:11:26.034"
        }
    ]
}

The error is coming from the await es.index({ index, type, id, body, refresh })

Tried many times with different settings, changed in config, etc. but I keep on getting the same error. I also enabled the error logging for ES but that did not provide any insights.

**Comment by tvnoppen** [comment]
Ok, seems to be a permissions issue or assigning the correct resources. I did set the permissions as described in the provided link, but apparently that is not enough. Will do some more digging to see what it is and it might help others in the future

**Comment by tvnoppen** [comment]
Found out what the permissions and resource should be. Hopefully this will help someone else as well.
`        {
            "Action": [
                "es:ESHttp*",
                "es:DescribeElasticsearchDomain",
                "es:DescribeElasticsearchDomainConfig"
            ],
            "Resource": "arn:aws:es:eu-west-1:<account>:domain/<domain>/*",
            "Effect": "Allow"
        },`
