### ISSUE TITLE
Issue with async

### ISSUE THREAD

**Issue by tonycam14** [matrus2/dynamodb-stream-elasticsearch#5]
Getting this error, looks like it has somthing to do with the async 

Function Logs

Syntax error in module 'Products/DynamoDBTrigger/index': SyntaxError
exports.pushStream = async (
  SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/Products/DynamoDBTrigger/index.js:1:86)

**Comment by matrus2** [comment]
Which version of node you are using?

**Comment by tonycam14** [comment]
Crap... never mind lol sorry
